/********************************************************************************
** Form generated from reading UI file 'nm_gui_nowotny_et_al_2008.ui'
**
** Created by: Qt User Interface Compiler version 5.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NM_GUI_NOWOTNY_ET_AL_2008_H
#define UI_NM_GUI_NOWOTNY_ET_AL_2008_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_NM_GUI_Nowotny_et_al_2008
{
public:
    QDoubleSpinBox *doubleSpinBox_i;
    QLabel *label;
    QLabel *label_2;
    QDoubleSpinBox *doubleSpinBox_ioffset;
    QLabel *label_3;
    QDoubleSpinBox *doubleSpinBox_iscale;
    QLabel *label_4;
    QDoubleSpinBox *doubleSpinBox_Cms;
    QLabel *label_5;
    QDoubleSpinBox *doubleSpinBox_Cma;
    QLabel *label_6;
    QDoubleSpinBox *doubleSpinBox_AreaSoma;
    QLabel *label_7;
    QDoubleSpinBox *doubleSpinBox_gvv;
    QLabel *label_8;
    QDoubleSpinBox *doubleSpinBox_AreaAxon;
    QLabel *label_9;
    QDoubleSpinBox *doubleSpinBox_gna;
    QLabel *label_10;
    QDoubleSpinBox *doubleSpinBox_Vna;
    QDoubleSpinBox *doubleSpinBox_gkd;
    QDoubleSpinBox *doubleSpinBox_Vkd;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QDoubleSpinBox *doubleSpinBox_Pca;
    QDoubleSpinBox *doubleSpinBox_Caout;
    QLabel *label_15;
    QLabel *label_16;
    QDoubleSpinBox *doubleSpinBox_RTF;
    QDoubleSpinBox *doubleSpinBox_Ca0;
    QLabel *label_17;
    QDoubleSpinBox *doubleSpinBox_cica;
    QLabel *label_18;
    QLabel *label_19;
    QDoubleSpinBox *doubleSpinBox_khcat;
    QDoubleSpinBox *doubleSpinBox_Vmcat;
    QLabel *label_20;
    QLabel *label_21;
    QDoubleSpinBox *doubleSpinBox_kmcat;
    QDoubleSpinBox *doubleSpinBox_Vhcat;
    QLabel *label_22;
    QDoubleSpinBox *doubleSpinBox_gcat;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QDoubleSpinBox *doubleSpinBox_Shcat;
    QDoubleSpinBox *doubleSpinBox_Smcat;
    QDoubleSpinBox *doubleSpinBox_Vkhcat;
    QDoubleSpinBox *doubleSpinBox_Skhcat;
    QLabel *label_27;
    QLabel *label_28;
    QDoubleSpinBox *doubleSpinBox_Smcas;
    QDoubleSpinBox *doubleSpinBox_kmcas;
    QLabel *label_29;
    QDoubleSpinBox *doubleSpinBox_gcas;
    QDoubleSpinBox *doubleSpinBox_Vmcas;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QDoubleSpinBox *doubleSpinBox_Vmkca1;
    QDoubleSpinBox *doubleSpinBox_Smkca2;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QDoubleSpinBox *doubleSpinBox_khkca;
    QLabel *label_44;
    QLabel *label_45;
    QDoubleSpinBox *doubleSpinBox_Vkca;
    QDoubleSpinBox *doubleSpinBox_kmkca;
    QDoubleSpinBox *doubleSpinBox_gkca;
    QDoubleSpinBox *doubleSpinBox_f;
    QLabel *label_46;
    QDoubleSpinBox *doubleSpinBox_Smkca1;
    QLabel *label_47;
    QDoubleSpinBox *doubleSpinBox_Vmkca2;
    QDoubleSpinBox *doubleSpinBox_kca;
    QLabel *label_48;
    QDoubleSpinBox *doubleSpinBox_chkca2;
    QLabel *label_49;
    QDoubleSpinBox *doubleSpinBox_cmkca;
    QDoubleSpinBox *doubleSpinBox_chkca1;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QDoubleSpinBox *doubleSpinBox_kha2;
    QDoubleSpinBox *doubleSpinBox_kma;
    QLabel *label_53;
    QDoubleSpinBox *doubleSpinBox_Vkha2;
    QDoubleSpinBox *doubleSpinBox_Va;
    QLabel *label_54;
    QLabel *label_55;
    QDoubleSpinBox *doubleSpinBox_Vma;
    QDoubleSpinBox *doubleSpinBox_ga;
    QDoubleSpinBox *doubleSpinBox_Sma;
    QDoubleSpinBox *doubleSpinBox_Sha;
    QLabel *label_56;
    QLabel *label_57;
    QDoubleSpinBox *doubleSpinBox_Skha2;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QDoubleSpinBox *doubleSpinBox_kha1;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QDoubleSpinBox *doubleSpinBox_Vaa;
    QDoubleSpinBox *doubleSpinBox_Vha;
    QLabel *label_64;
    QDoubleSpinBox *doubleSpinBox_Saa;
    QLabel *label_65;
    QDoubleSpinBox *doubleSpinBox_Vl;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QDoubleSpinBox *doubleSpinBox_gla;
    QLabel *label_69;
    QDoubleSpinBox *doubleSpinBox_gls;
    QDoubleSpinBox *doubleSpinBox_Skmh;
    QLabel *label_70;
    QLabel *label_71;
    QDoubleSpinBox *doubleSpinBox_gh;
    QLabel *label_72;
    QDoubleSpinBox *doubleSpinBox_Vmh;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QDoubleSpinBox *doubleSpinBox_Vh;
    QDoubleSpinBox *doubleSpinBox_Smh;
    QDoubleSpinBox *doubleSpinBox_kmh;
    QLabel *label_76;
    QDoubleSpinBox *doubleSpinBox_Vkmh;
    QLabel *label_77;
    QDoubleSpinBox *doubleSpinBox_Skmm;
    QLabel *label_78;
    QLabel *label_79;
    QDoubleSpinBox *doubleSpinBox_gm;
    QLabel *label_80;
    QDoubleSpinBox *doubleSpinBox_Vmm;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QDoubleSpinBox *doubleSpinBox_Vm;
    QDoubleSpinBox *doubleSpinBox_Vkmm;
    QDoubleSpinBox *doubleSpinBox_kmm;
    QLabel *label_84;
    QDoubleSpinBox *doubleSpinBox_Smm;
    QLabel *label_85;
    QDoubleSpinBox *doubleSpinBox_V;
    QLabel *label_86;
    QDoubleSpinBox *doubleSpinBox_Vaxon;
    QLabel *label_87;
    QDoubleSpinBox *doubleSpinBox_hna;
    QDoubleSpinBox *doubleSpinBox_mna;
    QLabel *label_88;
    QLabel *label_89;
    QDoubleSpinBox *doubleSpinBox_hcat;
    QDoubleSpinBox *doubleSpinBox_mcat;
    QDoubleSpinBox *doubleSpinBox_mkca;
    QDoubleSpinBox *doubleSpinBox_mcas;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QDoubleSpinBox *doubleSpinBox_mkd;
    QDoubleSpinBox *doubleSpinBox_hkca;
    QDoubleSpinBox *doubleSpinBox_Ca;
    QDoubleSpinBox *doubleSpinBox_ha1;
    QDoubleSpinBox *doubleSpinBox_mm;
    QLabel *label_94;
    QDoubleSpinBox *doubleSpinBox_ma;
    QDoubleSpinBox *doubleSpinBox_ha2;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_101;
    QDoubleSpinBox *doubleSpinBox_mh;
    QLabel *label_102;
    QGroupBox *groupBox_IntegrationMethod;
    QComboBox *comboBoxIntegrationMethod;
    QPushButton *pushButton_accept;

    void setupUi(QWidget *NM_GUI_Nowotny_et_al_2008)
    {
        if (NM_GUI_Nowotny_et_al_2008->objectName().isEmpty())
            NM_GUI_Nowotny_et_al_2008->setObjectName(QStringLiteral("NM_GUI_Nowotny_et_al_2008"));
        NM_GUI_Nowotny_et_al_2008->setWindowModality(Qt::ApplicationModal);
        NM_GUI_Nowotny_et_al_2008->resize(1003, 664);
        doubleSpinBox_i = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_i->setObjectName(QStringLiteral("doubleSpinBox_i"));
        doubleSpinBox_i->setGeometry(QRect(92, 34, 101, 24));
        doubleSpinBox_i->setDecimals(6);
        doubleSpinBox_i->setMinimum(-9999);
        doubleSpinBox_i->setMaximum(9999.99);
        doubleSpinBox_i->setValue(-6);
        label = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(44, 38, 61, 15));
        label_2 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(31, 70, 61, 15));
        doubleSpinBox_ioffset = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_ioffset->setObjectName(QStringLiteral("doubleSpinBox_ioffset"));
        doubleSpinBox_ioffset->setGeometry(QRect(92, 66, 101, 24));
        doubleSpinBox_ioffset->setDecimals(6);
        doubleSpinBox_ioffset->setMinimum(-9999);
        doubleSpinBox_ioffset->setMaximum(9999.99);
        doubleSpinBox_ioffset->setValue(-2);
        label_3 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(31, 100, 61, 15));
        doubleSpinBox_iscale = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_iscale->setObjectName(QStringLiteral("doubleSpinBox_iscale"));
        doubleSpinBox_iscale->setGeometry(QRect(92, 96, 101, 24));
        doubleSpinBox_iscale->setDecimals(6);
        doubleSpinBox_iscale->setMinimum(-9999);
        doubleSpinBox_iscale->setMaximum(9999.99);
        doubleSpinBox_iscale->setValue(0.012225);
        label_4 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(14, 154, 71, 16));
        doubleSpinBox_Cms = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Cms->setObjectName(QStringLiteral("doubleSpinBox_Cms"));
        doubleSpinBox_Cms->setGeometry(QRect(92, 151, 101, 24));
        doubleSpinBox_Cms->setDecimals(6);
        doubleSpinBox_Cms->setMinimum(-9999);
        doubleSpinBox_Cms->setMaximum(9999.99);
        doubleSpinBox_Cms->setValue(0.05439);
        label_5 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(16, 185, 61, 15));
        doubleSpinBox_Cma = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Cma->setObjectName(QStringLiteral("doubleSpinBox_Cma"));
        doubleSpinBox_Cma->setGeometry(QRect(92, 181, 101, 24));
        doubleSpinBox_Cma->setDecimals(6);
        doubleSpinBox_Cma->setMinimum(-9999);
        doubleSpinBox_Cma->setMaximum(9999.99);
        doubleSpinBox_Cma->setValue(0.114831);
        label_6 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(9, 213, 81, 16));
        doubleSpinBox_AreaSoma = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_AreaSoma->setObjectName(QStringLiteral("doubleSpinBox_AreaSoma"));
        doubleSpinBox_AreaSoma->setGeometry(QRect(92, 211, 101, 24));
        doubleSpinBox_AreaSoma->setDecimals(6);
        doubleSpinBox_AreaSoma->setMinimum(-9999);
        doubleSpinBox_AreaSoma->setMaximum(9999.99);
        doubleSpinBox_AreaSoma->setValue(0.9);
        label_7 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(34, 275, 61, 15));
        doubleSpinBox_gvv = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gvv->setObjectName(QStringLiteral("doubleSpinBox_gvv"));
        doubleSpinBox_gvv->setGeometry(QRect(92, 271, 101, 24));
        doubleSpinBox_gvv->setDecimals(6);
        doubleSpinBox_gvv->setMinimum(-9999);
        doubleSpinBox_gvv->setMaximum(9999.99);
        doubleSpinBox_gvv->setValue(0.004017);
        label_8 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(12, 242, 81, 20));
        doubleSpinBox_AreaAxon = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_AreaAxon->setObjectName(QStringLiteral("doubleSpinBox_AreaAxon"));
        doubleSpinBox_AreaAxon->setGeometry(QRect(92, 241, 101, 24));
        doubleSpinBox_AreaAxon->setDecimals(6);
        doubleSpinBox_AreaAxon->setMinimum(-9999);
        doubleSpinBox_AreaAxon->setMaximum(9999.99);
        doubleSpinBox_AreaAxon->setValue(1);
        label_9 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(34, 332, 61, 15));
        doubleSpinBox_gna = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gna->setObjectName(QStringLiteral("doubleSpinBox_gna"));
        doubleSpinBox_gna->setGeometry(QRect(92, 328, 101, 24));
        doubleSpinBox_gna->setDecimals(6);
        doubleSpinBox_gna->setMinimum(-9999);
        doubleSpinBox_gna->setMaximum(9999.99);
        doubleSpinBox_gna->setValue(7.15);
        label_10 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(34, 362, 61, 15));
        doubleSpinBox_Vna = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vna->setObjectName(QStringLiteral("doubleSpinBox_Vna"));
        doubleSpinBox_Vna->setGeometry(QRect(92, 358, 101, 24));
        doubleSpinBox_Vna->setDecimals(6);
        doubleSpinBox_Vna->setMinimum(-9999);
        doubleSpinBox_Vna->setMaximum(9999.99);
        doubleSpinBox_Vna->setValue(50);
        doubleSpinBox_gkd = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gkd->setObjectName(QStringLiteral("doubleSpinBox_gkd"));
        doubleSpinBox_gkd->setGeometry(QRect(92, 418, 101, 24));
        doubleSpinBox_gkd->setDecimals(6);
        doubleSpinBox_gkd->setMinimum(-9999);
        doubleSpinBox_gkd->setMaximum(9999.99);
        doubleSpinBox_gkd->setValue(1.43);
        doubleSpinBox_Vkd = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vkd->setObjectName(QStringLiteral("doubleSpinBox_Vkd"));
        doubleSpinBox_Vkd->setGeometry(QRect(92, 448, 101, 24));
        doubleSpinBox_Vkd->setDecimals(6);
        doubleSpinBox_Vkd->setMinimum(-9999);
        doubleSpinBox_Vkd->setMaximum(9999.99);
        doubleSpinBox_Vkd->setValue(-72);
        label_11 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(34, 452, 61, 15));
        label_12 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(34, 422, 61, 15));
        label_13 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(238, 97, 61, 15));
        label_14 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(232, 127, 61, 15));
        doubleSpinBox_Pca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Pca->setObjectName(QStringLiteral("doubleSpinBox_Pca"));
        doubleSpinBox_Pca->setGeometry(QRect(287, 93, 101, 24));
        doubleSpinBox_Pca->setDecimals(6);
        doubleSpinBox_Pca->setMinimum(-9999);
        doubleSpinBox_Pca->setMaximum(9999.99);
        doubleSpinBox_Pca->setValue(0.00156);
        doubleSpinBox_Caout = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Caout->setObjectName(QStringLiteral("doubleSpinBox_Caout"));
        doubleSpinBox_Caout->setGeometry(QRect(287, 123, 101, 24));
        doubleSpinBox_Caout->setDecimals(6);
        doubleSpinBox_Caout->setMinimum(-99999);
        doubleSpinBox_Caout->setMaximum(100000);
        doubleSpinBox_Caout->setValue(15123.5);
        label_15 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(238, 67, 61, 15));
        label_16 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(238, 157, 61, 15));
        doubleSpinBox_RTF = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_RTF->setObjectName(QStringLiteral("doubleSpinBox_RTF"));
        doubleSpinBox_RTF->setGeometry(QRect(287, 63, 101, 24));
        doubleSpinBox_RTF->setDecimals(6);
        doubleSpinBox_RTF->setMinimum(-9999);
        doubleSpinBox_RTF->setMaximum(9999.99);
        doubleSpinBox_RTF->setValue(11.4866);
        doubleSpinBox_Ca0 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Ca0->setObjectName(QStringLiteral("doubleSpinBox_Ca0"));
        doubleSpinBox_Ca0->setGeometry(QRect(287, 153, 101, 24));
        doubleSpinBox_Ca0->setDecimals(6);
        doubleSpinBox_Ca0->setMinimum(-9999);
        doubleSpinBox_Ca0->setMaximum(9999.99);
        doubleSpinBox_Ca0->setValue(0.02);
        label_17 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(238, 37, 61, 15));
        doubleSpinBox_cica = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_cica->setObjectName(QStringLiteral("doubleSpinBox_cica"));
        doubleSpinBox_cica->setGeometry(QRect(287, 33, 101, 24));
        doubleSpinBox_cica->setDecimals(6);
        doubleSpinBox_cica->setMinimum(-9999);
        doubleSpinBox_cica->setMaximum(9999.99);
        doubleSpinBox_cica->setValue(0.050496);
        label_18 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(234, 302, 61, 15));
        label_19 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(232, 332, 61, 15));
        doubleSpinBox_khcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_khcat->setObjectName(QStringLiteral("doubleSpinBox_khcat"));
        doubleSpinBox_khcat->setGeometry(QRect(286, 298, 101, 24));
        doubleSpinBox_khcat->setDecimals(6);
        doubleSpinBox_khcat->setMinimum(-9999);
        doubleSpinBox_khcat->setMaximum(9999.99);
        doubleSpinBox_khcat->setValue(0.02);
        doubleSpinBox_Vmcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vmcat->setObjectName(QStringLiteral("doubleSpinBox_Vmcat"));
        doubleSpinBox_Vmcat->setGeometry(QRect(286, 328, 101, 24));
        doubleSpinBox_Vmcat->setDecimals(6);
        doubleSpinBox_Vmcat->setMinimum(-9999);
        doubleSpinBox_Vmcat->setMaximum(9999.99);
        doubleSpinBox_Vmcat->setValue(15);
        label_20 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(232, 272, 61, 15));
        label_21 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(234, 362, 61, 15));
        doubleSpinBox_kmcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kmcat->setObjectName(QStringLiteral("doubleSpinBox_kmcat"));
        doubleSpinBox_kmcat->setGeometry(QRect(286, 268, 101, 24));
        doubleSpinBox_kmcat->setDecimals(6);
        doubleSpinBox_kmcat->setMinimum(-9999);
        doubleSpinBox_kmcat->setMaximum(9999.99);
        doubleSpinBox_kmcat->setValue(0.045);
        doubleSpinBox_Vhcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vhcat->setObjectName(QStringLiteral("doubleSpinBox_Vhcat"));
        doubleSpinBox_Vhcat->setGeometry(QRect(286, 358, 101, 24));
        doubleSpinBox_Vhcat->setDecimals(6);
        doubleSpinBox_Vhcat->setMinimum(-9999);
        doubleSpinBox_Vhcat->setMaximum(9999.99);
        doubleSpinBox_Vhcat->setValue(-40);
        label_22 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(237, 242, 61, 15));
        doubleSpinBox_gcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gcat->setObjectName(QStringLiteral("doubleSpinBox_gcat"));
        doubleSpinBox_gcat->setGeometry(QRect(286, 238, 101, 24));
        doubleSpinBox_gcat->setDecimals(6);
        doubleSpinBox_gcat->setMinimum(-9999);
        doubleSpinBox_gcat->setMaximum(9999.99);
        doubleSpinBox_gcat->setValue(0.12478);
        label_23 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(233, 482, 61, 15));
        label_24 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(233, 422, 61, 15));
        label_25 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(232, 392, 61, 15));
        label_26 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(232, 452, 61, 15));
        doubleSpinBox_Shcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Shcat->setObjectName(QStringLiteral("doubleSpinBox_Shcat"));
        doubleSpinBox_Shcat->setGeometry(QRect(286, 418, 101, 24));
        doubleSpinBox_Shcat->setDecimals(6);
        doubleSpinBox_Shcat->setMinimum(-9999);
        doubleSpinBox_Shcat->setMaximum(9999.99);
        doubleSpinBox_Shcat->setValue(3.2);
        doubleSpinBox_Smcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Smcat->setObjectName(QStringLiteral("doubleSpinBox_Smcat"));
        doubleSpinBox_Smcat->setGeometry(QRect(286, 388, 101, 24));
        doubleSpinBox_Smcat->setDecimals(6);
        doubleSpinBox_Smcat->setMinimum(-9999);
        doubleSpinBox_Smcat->setMaximum(9999.99);
        doubleSpinBox_Smcat->setValue(-9.8);
        doubleSpinBox_Vkhcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vkhcat->setObjectName(QStringLiteral("doubleSpinBox_Vkhcat"));
        doubleSpinBox_Vkhcat->setGeometry(QRect(286, 448, 101, 24));
        doubleSpinBox_Vkhcat->setDecimals(6);
        doubleSpinBox_Vkhcat->setMinimum(-9999);
        doubleSpinBox_Vkhcat->setMaximum(9999.99);
        doubleSpinBox_Vkhcat->setValue(-15);
        doubleSpinBox_Skhcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Skhcat->setObjectName(QStringLiteral("doubleSpinBox_Skhcat"));
        doubleSpinBox_Skhcat->setGeometry(QRect(286, 478, 101, 24));
        doubleSpinBox_Skhcat->setDecimals(6);
        doubleSpinBox_Skhcat->setMinimum(-9999);
        doubleSpinBox_Skhcat->setMaximum(9999.99);
        doubleSpinBox_Skhcat->setValue(-10);
        label_27 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(232, 566, 61, 15));
        label_28 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(232, 596, 61, 15));
        doubleSpinBox_Smcas = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Smcas->setObjectName(QStringLiteral("doubleSpinBox_Smcas"));
        doubleSpinBox_Smcas->setGeometry(QRect(285, 622, 101, 24));
        doubleSpinBox_Smcas->setDecimals(6);
        doubleSpinBox_Smcas->setMinimum(-9999);
        doubleSpinBox_Smcas->setMaximum(9999.99);
        doubleSpinBox_Smcas->setValue(-4.43083);
        doubleSpinBox_kmcas = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kmcas->setObjectName(QStringLiteral("doubleSpinBox_kmcas"));
        doubleSpinBox_kmcas->setGeometry(QRect(285, 562, 101, 24));
        doubleSpinBox_kmcas->setDecimals(6);
        doubleSpinBox_kmcas->setMinimum(-9999);
        doubleSpinBox_kmcas->setMaximum(9999.99);
        doubleSpinBox_kmcas->setValue(0.060864);
        label_29 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(236, 536, 61, 15));
        doubleSpinBox_gcas = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gcas->setObjectName(QStringLiteral("doubleSpinBox_gcas"));
        doubleSpinBox_gcas->setGeometry(QRect(285, 532, 101, 24));
        doubleSpinBox_gcas->setDecimals(6);
        doubleSpinBox_gcas->setMinimum(-9999);
        doubleSpinBox_gcas->setMaximum(9999.99);
        doubleSpinBox_gcas->setValue(0.071421);
        doubleSpinBox_Vmcas = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vmcas->setObjectName(QStringLiteral("doubleSpinBox_Vmcas"));
        doubleSpinBox_Vmcas->setGeometry(QRect(285, 592, 101, 24));
        doubleSpinBox_Vmcas->setDecimals(6);
        doubleSpinBox_Vmcas->setMinimum(-9999);
        doubleSpinBox_Vmcas->setMaximum(9999.99);
        doubleSpinBox_Vmcas->setValue(29.1336);
        label_30 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(232, 626, 61, 15));
        label_31 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 10, 91, 16));
        QFont font;
        font.setFamily(QStringLiteral("DejaVu Sans Mono"));
        font.setBold(true);
        font.setWeight(75);
        label_31->setFont(font);
        label_32 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 130, 181, 16));
        label_32->setFont(font);
        label_33 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 310, 61, 15));
        label_33->setFont(font);
        label_34 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 400, 61, 15));
        label_34->setFont(font);
        label_35 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(230, 10, 61, 15));
        label_35->setFont(font);
        label_36 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(230, 220, 61, 15));
        label_36->setFont(font);
        label_37 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(230, 512, 61, 15));
        label_37->setFont(font);
        label_38 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(422, 216, 61, 15));
        doubleSpinBox_Vmkca1 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vmkca1->setObjectName(QStringLiteral("doubleSpinBox_Vmkca1"));
        doubleSpinBox_Vmkca1->setGeometry(QRect(486, 152, 101, 24));
        doubleSpinBox_Vmkca1->setDecimals(6);
        doubleSpinBox_Vmkca1->setMinimum(-9999);
        doubleSpinBox_Vmkca1->setMaximum(9999.99);
        doubleSpinBox_Smkca2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Smkca2->setObjectName(QStringLiteral("doubleSpinBox_Smkca2"));
        doubleSpinBox_Smkca2->setGeometry(QRect(486, 242, 101, 24));
        doubleSpinBox_Smkca2->setDecimals(6);
        doubleSpinBox_Smkca2->setMinimum(-9999);
        doubleSpinBox_Smkca2->setMaximum(9999.99);
        doubleSpinBox_Smkca2->setValue(-5);
        label_39 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(422, 156, 61, 15));
        label_40 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(429, 96, 61, 15));
        label_41 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(432, 36, 61, 15));
        label_42 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(432, 66, 61, 15));
        label_43 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(442, 276, 61, 15));
        doubleSpinBox_khkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_khkca->setObjectName(QStringLiteral("doubleSpinBox_khkca"));
        doubleSpinBox_khkca->setGeometry(QRect(486, 122, 101, 24));
        doubleSpinBox_khkca->setDecimals(6);
        doubleSpinBox_khkca->setMinimum(-9999);
        doubleSpinBox_khkca->setMaximum(9999.99);
        doubleSpinBox_khkca->setValue(0.035);
        label_44 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(429, 126, 61, 15));
        label_45 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(422, 246, 61, 15));
        doubleSpinBox_Vkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vkca->setObjectName(QStringLiteral("doubleSpinBox_Vkca"));
        doubleSpinBox_Vkca->setGeometry(QRect(486, 62, 101, 24));
        doubleSpinBox_Vkca->setDecimals(6);
        doubleSpinBox_Vkca->setMinimum(-9999);
        doubleSpinBox_Vkca->setMaximum(9999.99);
        doubleSpinBox_Vkca->setValue(-72);
        doubleSpinBox_kmkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kmkca->setObjectName(QStringLiteral("doubleSpinBox_kmkca"));
        doubleSpinBox_kmkca->setGeometry(QRect(486, 92, 101, 24));
        doubleSpinBox_kmkca->setDecimals(6);
        doubleSpinBox_kmkca->setMinimum(-9999);
        doubleSpinBox_kmkca->setMaximum(9999.99);
        doubleSpinBox_kmkca->setValue(0.6);
        doubleSpinBox_gkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gkca->setObjectName(QStringLiteral("doubleSpinBox_gkca"));
        doubleSpinBox_gkca->setGeometry(QRect(486, 32, 101, 24));
        doubleSpinBox_gkca->setDecimals(6);
        doubleSpinBox_gkca->setMinimum(-9999);
        doubleSpinBox_gkca->setMaximum(9999.99);
        doubleSpinBox_gkca->setValue(1.66361);
        doubleSpinBox_f = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_f->setObjectName(QStringLiteral("doubleSpinBox_f"));
        doubleSpinBox_f->setGeometry(QRect(486, 272, 101, 24));
        doubleSpinBox_f->setDecimals(6);
        doubleSpinBox_f->setMinimum(-9999);
        doubleSpinBox_f->setMaximum(9999.99);
        doubleSpinBox_f->setValue(0.6);
        label_46 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(422, 186, 61, 15));
        doubleSpinBox_Smkca1 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Smkca1->setObjectName(QStringLiteral("doubleSpinBox_Smkca1"));
        doubleSpinBox_Smkca1->setGeometry(QRect(486, 212, 101, 24));
        doubleSpinBox_Smkca1->setDecimals(6);
        doubleSpinBox_Smkca1->setMinimum(-9999);
        doubleSpinBox_Smkca1->setMaximum(9999.99);
        doubleSpinBox_Smkca1->setValue(-23);
        label_47 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(420, 10, 61, 15));
        label_47->setFont(font);
        doubleSpinBox_Vmkca2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vmkca2->setObjectName(QStringLiteral("doubleSpinBox_Vmkca2"));
        doubleSpinBox_Vmkca2->setGeometry(QRect(486, 182, 101, 24));
        doubleSpinBox_Vmkca2->setDecimals(6);
        doubleSpinBox_Vmkca2->setMinimum(-9999);
        doubleSpinBox_Vmkca2->setMaximum(9999.99);
        doubleSpinBox_Vmkca2->setValue(-16);
        doubleSpinBox_kca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kca->setObjectName(QStringLiteral("doubleSpinBox_kca"));
        doubleSpinBox_kca->setGeometry(QRect(287, 182, 101, 24));
        doubleSpinBox_kca->setDecimals(6);
        doubleSpinBox_kca->setMinimum(-9999);
        doubleSpinBox_kca->setMaximum(9999.99);
        doubleSpinBox_kca->setValue(0.017299);
        label_48 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(238, 186, 61, 15));
        doubleSpinBox_chkca2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_chkca2->setObjectName(QStringLiteral("doubleSpinBox_chkca2"));
        doubleSpinBox_chkca2->setGeometry(QRect(486, 362, 101, 24));
        doubleSpinBox_chkca2->setDecimals(6);
        doubleSpinBox_chkca2->setMinimum(-9999);
        doubleSpinBox_chkca2->setMaximum(9999.99);
        doubleSpinBox_chkca2->setValue(0.6);
        label_49 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(422, 306, 61, 15));
        doubleSpinBox_cmkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_cmkca->setObjectName(QStringLiteral("doubleSpinBox_cmkca"));
        doubleSpinBox_cmkca->setGeometry(QRect(486, 302, 101, 24));
        doubleSpinBox_cmkca->setDecimals(6);
        doubleSpinBox_cmkca->setMinimum(-9999);
        doubleSpinBox_cmkca->setMaximum(9999.99);
        doubleSpinBox_cmkca->setValue(2.5);
        doubleSpinBox_chkca1 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_chkca1->setObjectName(QStringLiteral("doubleSpinBox_chkca1"));
        doubleSpinBox_chkca1->setGeometry(QRect(486, 332, 101, 24));
        doubleSpinBox_chkca1->setDecimals(6);
        doubleSpinBox_chkca1->setMinimum(-9999);
        doubleSpinBox_chkca1->setMaximum(9999.99);
        doubleSpinBox_chkca1->setValue(0.7);
        label_50 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(422, 366, 61, 15));
        label_51 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(422, 336, 61, 15));
        label_52 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(632, 186, 61, 15));
        doubleSpinBox_kha2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kha2->setObjectName(QStringLiteral("doubleSpinBox_kha2"));
        doubleSpinBox_kha2->setGeometry(QRect(687, 152, 101, 24));
        doubleSpinBox_kha2->setDecimals(6);
        doubleSpinBox_kha2->setMinimum(-9999);
        doubleSpinBox_kha2->setMaximum(9999.99);
        doubleSpinBox_kha2->setValue(0.0036);
        doubleSpinBox_kma = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kma->setObjectName(QStringLiteral("doubleSpinBox_kma"));
        doubleSpinBox_kma->setGeometry(QRect(687, 92, 101, 24));
        doubleSpinBox_kma->setDecimals(6);
        doubleSpinBox_kma->setMinimum(-9999);
        doubleSpinBox_kma->setMaximum(9999.99);
        doubleSpinBox_kma->setValue(0.14);
        label_53 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(637, 36, 61, 15));
        doubleSpinBox_Vkha2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vkha2->setObjectName(QStringLiteral("doubleSpinBox_Vkha2"));
        doubleSpinBox_Vkha2->setGeometry(QRect(687, 242, 101, 24));
        doubleSpinBox_Vkha2->setDecimals(6);
        doubleSpinBox_Vkha2->setMinimum(-9999);
        doubleSpinBox_Vkha2->setMaximum(9999.99);
        doubleSpinBox_Vkha2->setValue(-40);
        doubleSpinBox_Va = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Va->setObjectName(QStringLiteral("doubleSpinBox_Va"));
        doubleSpinBox_Va->setGeometry(QRect(687, 62, 101, 24));
        doubleSpinBox_Va->setDecimals(6);
        doubleSpinBox_Va->setMinimum(-9999);
        doubleSpinBox_Va->setMaximum(9999.99);
        doubleSpinBox_Va->setValue(-72);
        label_54 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(632, 156, 61, 15));
        label_55 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(636, 66, 61, 15));
        doubleSpinBox_Vma = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vma->setObjectName(QStringLiteral("doubleSpinBox_Vma"));
        doubleSpinBox_Vma->setGeometry(QRect(687, 182, 101, 24));
        doubleSpinBox_Vma->setDecimals(6);
        doubleSpinBox_Vma->setMinimum(-9999);
        doubleSpinBox_Vma->setMaximum(9999.99);
        doubleSpinBox_Vma->setValue(-12);
        doubleSpinBox_ga = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_ga->setObjectName(QStringLiteral("doubleSpinBox_ga"));
        doubleSpinBox_ga->setGeometry(QRect(687, 32, 101, 24));
        doubleSpinBox_ga->setDecimals(6);
        doubleSpinBox_ga->setMinimum(-9999);
        doubleSpinBox_ga->setMaximum(9999.99);
        doubleSpinBox_ga->setValue(0.800879);
        doubleSpinBox_Sma = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Sma->setObjectName(QStringLiteral("doubleSpinBox_Sma"));
        doubleSpinBox_Sma->setGeometry(QRect(687, 302, 101, 24));
        doubleSpinBox_Sma->setDecimals(6);
        doubleSpinBox_Sma->setMinimum(-9999);
        doubleSpinBox_Sma->setMaximum(9999.99);
        doubleSpinBox_Sma->setValue(-26);
        doubleSpinBox_Sha = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Sha->setObjectName(QStringLiteral("doubleSpinBox_Sha"));
        doubleSpinBox_Sha->setGeometry(QRect(687, 332, 101, 24));
        doubleSpinBox_Sha->setDecimals(6);
        doubleSpinBox_Sha->setMinimum(-9999);
        doubleSpinBox_Sha->setMaximum(9999.99);
        doubleSpinBox_Sha->setValue(6);
        label_56 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(632, 216, 61, 15));
        label_57 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(628, 246, 61, 15));
        doubleSpinBox_Skha2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Skha2->setObjectName(QStringLiteral("doubleSpinBox_Skha2"));
        doubleSpinBox_Skha2->setGeometry(QRect(687, 362, 101, 24));
        doubleSpinBox_Skha2->setDecimals(6);
        doubleSpinBox_Skha2->setMinimum(-9999);
        doubleSpinBox_Skha2->setMaximum(9999.99);
        doubleSpinBox_Skha2->setValue(-12);
        label_58 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(632, 96, 61, 15));
        label_59 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(632, 126, 61, 15));
        label_60 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(632, 276, 61, 15));
        doubleSpinBox_kha1 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kha1->setObjectName(QStringLiteral("doubleSpinBox_kha1"));
        doubleSpinBox_kha1->setGeometry(QRect(687, 122, 101, 24));
        doubleSpinBox_kha1->setDecimals(6);
        doubleSpinBox_kha1->setMinimum(-9999);
        doubleSpinBox_kha1->setMaximum(9999.99);
        doubleSpinBox_kha1->setValue(0.05);
        label_61 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(632, 336, 61, 15));
        label_62 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(628, 366, 61, 15));
        label_63 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(630, 10, 61, 15));
        label_63->setFont(font);
        doubleSpinBox_Vaa = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vaa->setObjectName(QStringLiteral("doubleSpinBox_Vaa"));
        doubleSpinBox_Vaa->setGeometry(QRect(687, 272, 101, 24));
        doubleSpinBox_Vaa->setDecimals(6);
        doubleSpinBox_Vaa->setMinimum(-9999);
        doubleSpinBox_Vaa->setMaximum(9999.99);
        doubleSpinBox_Vaa->setValue(7);
        doubleSpinBox_Vha = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vha->setObjectName(QStringLiteral("doubleSpinBox_Vha"));
        doubleSpinBox_Vha->setGeometry(QRect(687, 212, 101, 24));
        doubleSpinBox_Vha->setDecimals(6);
        doubleSpinBox_Vha->setMinimum(-9999);
        doubleSpinBox_Vha->setMaximum(9999.99);
        doubleSpinBox_Vha->setValue(-62);
        label_64 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(632, 306, 61, 15));
        doubleSpinBox_Saa = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Saa->setObjectName(QStringLiteral("doubleSpinBox_Saa"));
        doubleSpinBox_Saa->setGeometry(QRect(687, 391, 101, 24));
        doubleSpinBox_Saa->setDecimals(6);
        doubleSpinBox_Saa->setMinimum(-9999);
        doubleSpinBox_Saa->setMaximum(9999.99);
        doubleSpinBox_Saa->setValue(-15);
        label_65 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(632, 395, 61, 15));
        doubleSpinBox_Vl = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vl->setObjectName(QStringLiteral("doubleSpinBox_Vl"));
        doubleSpinBox_Vl->setGeometry(QRect(92, 571, 101, 24));
        doubleSpinBox_Vl->setDecimals(6);
        doubleSpinBox_Vl->setMinimum(-9999);
        doubleSpinBox_Vl->setMaximum(9999.99);
        doubleSpinBox_Vl->setValue(-50);
        label_66 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(43, 575, 61, 15));
        label_67 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(23, 515, 61, 15));
        label_68 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(27, 545, 61, 15));
        doubleSpinBox_gla = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gla->setObjectName(QStringLiteral("doubleSpinBox_gla"));
        doubleSpinBox_gla->setGeometry(QRect(92, 541, 101, 24));
        doubleSpinBox_gla->setDecimals(6);
        doubleSpinBox_gla->setMinimum(-9999);
        doubleSpinBox_gla->setMaximum(9999.99);
        doubleSpinBox_gla->setValue(0.001004);
        label_69 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(10, 489, 61, 15));
        label_69->setFont(font);
        doubleSpinBox_gls = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gls->setObjectName(QStringLiteral("doubleSpinBox_gls"));
        doubleSpinBox_gls->setGeometry(QRect(92, 511, 101, 24));
        doubleSpinBox_gls->setDecimals(6);
        doubleSpinBox_gls->setMinimum(-9999);
        doubleSpinBox_gls->setMaximum(9999.99);
        doubleSpinBox_gls->setValue(0.00069);
        doubleSpinBox_Skmh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Skmh->setObjectName(QStringLiteral("doubleSpinBox_Skmh"));
        doubleSpinBox_Skmh->setGeometry(QRect(484, 628, 101, 24));
        doubleSpinBox_Skmh->setDecimals(6);
        doubleSpinBox_Skmh->setMinimum(-9999);
        doubleSpinBox_Skmh->setMaximum(9999.99);
        doubleSpinBox_Skmh->setValue(-21.6);
        label_70 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(432, 452, 61, 15));
        label_71 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(427, 512, 61, 15));
        doubleSpinBox_gh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gh->setObjectName(QStringLiteral("doubleSpinBox_gh"));
        doubleSpinBox_gh->setGeometry(QRect(484, 448, 101, 24));
        doubleSpinBox_gh->setDecimals(6);
        doubleSpinBox_gh->setMinimum(-9999);
        doubleSpinBox_gh->setMaximum(9999.99);
        doubleSpinBox_gh->setValue(0.012687);
        label_72 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(424, 572, 61, 15));
        doubleSpinBox_Vmh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vmh->setObjectName(QStringLiteral("doubleSpinBox_Vmh"));
        doubleSpinBox_Vmh->setGeometry(QRect(484, 538, 101, 24));
        doubleSpinBox_Vmh->setDecimals(6);
        doubleSpinBox_Vmh->setMinimum(-9999);
        doubleSpinBox_Vmh->setMaximum(9999.99);
        doubleSpinBox_Vmh->setValue(-70);
        label_73 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(432, 482, 61, 15));
        label_74 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(420, 426, 61, 15));
        label_74->setFont(font);
        label_75 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(427, 602, 61, 15));
        doubleSpinBox_Vh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vh->setObjectName(QStringLiteral("doubleSpinBox_Vh"));
        doubleSpinBox_Vh->setGeometry(QRect(484, 478, 101, 24));
        doubleSpinBox_Vh->setDecimals(6);
        doubleSpinBox_Vh->setMinimum(-9999);
        doubleSpinBox_Vh->setMaximum(9999.99);
        doubleSpinBox_Vh->setValue(-20);
        doubleSpinBox_Smh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Smh->setObjectName(QStringLiteral("doubleSpinBox_Smh"));
        doubleSpinBox_Smh->setGeometry(QRect(484, 598, 101, 24));
        doubleSpinBox_Smh->setDecimals(6);
        doubleSpinBox_Smh->setMinimum(-9999);
        doubleSpinBox_Smh->setMaximum(9999.99);
        doubleSpinBox_Smh->setValue(8);
        doubleSpinBox_kmh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kmh->setObjectName(QStringLiteral("doubleSpinBox_kmh"));
        doubleSpinBox_kmh->setGeometry(QRect(484, 508, 101, 24));
        doubleSpinBox_kmh->setDecimals(6);
        doubleSpinBox_kmh->setMinimum(-9999);
        doubleSpinBox_kmh->setMaximum(9999.99);
        doubleSpinBox_kmh->setValue(0.00033);
        label_76 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(425, 632, 61, 15));
        doubleSpinBox_Vkmh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vkmh->setObjectName(QStringLiteral("doubleSpinBox_Vkmh"));
        doubleSpinBox_Vkmh->setGeometry(QRect(484, 568, 101, 24));
        doubleSpinBox_Vkmh->setDecimals(6);
        doubleSpinBox_Vkmh->setMinimum(-9999);
        doubleSpinBox_Vkmh->setMaximum(9999.99);
        doubleSpinBox_Vkmh->setValue(-110);
        label_77 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(427, 542, 61, 15));
        doubleSpinBox_Skmm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Skmm->setObjectName(QStringLiteral("doubleSpinBox_Skmm"));
        doubleSpinBox_Skmm->setGeometry(QRect(688, 627, 101, 24));
        doubleSpinBox_Skmm->setDecimals(6);
        doubleSpinBox_Skmm->setMinimum(-9999);
        doubleSpinBox_Skmm->setMaximum(9999.99);
        doubleSpinBox_Skmm->setValue(-13.2567);
        label_78 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(634, 451, 61, 15));
        label_79 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(631, 511, 61, 15));
        doubleSpinBox_gm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_gm->setObjectName(QStringLiteral("doubleSpinBox_gm"));
        doubleSpinBox_gm->setGeometry(QRect(688, 447, 101, 24));
        doubleSpinBox_gm->setDecimals(6);
        doubleSpinBox_gm->setMinimum(-9999);
        doubleSpinBox_gm->setMaximum(9999.99);
        doubleSpinBox_gm->setValue(0.261304);
        label_80 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(630, 571, 61, 15));
        doubleSpinBox_Vmm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vmm->setObjectName(QStringLiteral("doubleSpinBox_Vmm"));
        doubleSpinBox_Vmm->setGeometry(QRect(688, 537, 101, 24));
        doubleSpinBox_Vmm->setDecimals(6);
        doubleSpinBox_Vmm->setMinimum(-9999);
        doubleSpinBox_Vmm->setMaximum(9999.99);
        doubleSpinBox_Vmm->setValue(-26.9916);
        label_81 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(634, 481, 61, 15));
        label_82 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(630, 425, 61, 15));
        label_82->setFont(font);
        label_83 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(627, 601, 61, 15));
        doubleSpinBox_Vm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vm->setObjectName(QStringLiteral("doubleSpinBox_Vm"));
        doubleSpinBox_Vm->setGeometry(QRect(688, 477, 101, 24));
        doubleSpinBox_Vm->setDecimals(6);
        doubleSpinBox_Vm->setMinimum(-9999);
        doubleSpinBox_Vm->setMaximum(9999.99);
        doubleSpinBox_Vm->setValue(-80);
        doubleSpinBox_Vkmm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vkmm->setObjectName(QStringLiteral("doubleSpinBox_Vkmm"));
        doubleSpinBox_Vkmm->setGeometry(QRect(688, 597, 101, 24));
        doubleSpinBox_Vkmm->setDecimals(6);
        doubleSpinBox_Vkmm->setMinimum(-9999);
        doubleSpinBox_Vkmm->setMaximum(9999.99);
        doubleSpinBox_Vkmm->setValue(-60.5788);
        doubleSpinBox_kmm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_kmm->setObjectName(QStringLiteral("doubleSpinBox_kmm"));
        doubleSpinBox_kmm->setGeometry(QRect(688, 507, 101, 24));
        doubleSpinBox_kmm->setDecimals(6);
        doubleSpinBox_kmm->setMinimum(-9999);
        doubleSpinBox_kmm->setMaximum(9999.99);
        doubleSpinBox_kmm->setValue(0.000139);
        label_84 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(628, 631, 61, 15));
        doubleSpinBox_Smm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Smm->setObjectName(QStringLiteral("doubleSpinBox_Smm"));
        doubleSpinBox_Smm->setGeometry(QRect(688, 567, 101, 24));
        doubleSpinBox_Smm->setDecimals(6);
        doubleSpinBox_Smm->setMinimum(-9999);
        doubleSpinBox_Smm->setMaximum(9999.99);
        doubleSpinBox_Smm->setValue(-5.95744);
        label_85 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(630, 541, 61, 15));
        doubleSpinBox_V = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_V->setObjectName(QStringLiteral("doubleSpinBox_V"));
        doubleSpinBox_V->setGeometry(QRect(886, 31, 101, 24));
        doubleSpinBox_V->setDecimals(6);
        doubleSpinBox_V->setMinimum(-9999);
        doubleSpinBox_V->setMaximum(9999.99);
        doubleSpinBox_V->setValue(-65.6753);
        label_86 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(850, 35, 61, 15));
        doubleSpinBox_Vaxon = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Vaxon->setObjectName(QStringLiteral("doubleSpinBox_Vaxon"));
        doubleSpinBox_Vaxon->setGeometry(QRect(886, 62, 101, 24));
        doubleSpinBox_Vaxon->setDecimals(6);
        doubleSpinBox_Vaxon->setMinimum(-9999);
        doubleSpinBox_Vaxon->setMaximum(9999.99);
        doubleSpinBox_Vaxon->setValue(-70.601);
        label_87 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(838, 66, 61, 15));
        doubleSpinBox_hna = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_hna->setObjectName(QStringLiteral("doubleSpinBox_hna"));
        doubleSpinBox_hna->setGeometry(QRect(885, 123, 101, 24));
        doubleSpinBox_hna->setDecimals(6);
        doubleSpinBox_hna->setMinimum(-9999);
        doubleSpinBox_hna->setMaximum(9999.99);
        doubleSpinBox_hna->setValue(0.999018);
        doubleSpinBox_mna = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mna->setObjectName(QStringLiteral("doubleSpinBox_mna"));
        doubleSpinBox_mna->setGeometry(QRect(885, 92, 101, 24));
        doubleSpinBox_mna->setDecimals(6);
        doubleSpinBox_mna->setMinimum(-9999);
        doubleSpinBox_mna->setMaximum(9999.99);
        doubleSpinBox_mna->setValue(0.00448);
        label_88 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(842, 96, 61, 15));
        label_89 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(845, 127, 61, 15));
        doubleSpinBox_hcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_hcat->setObjectName(QStringLiteral("doubleSpinBox_hcat"));
        doubleSpinBox_hcat->setGeometry(QRect(885, 183, 101, 24));
        doubleSpinBox_hcat->setDecimals(6);
        doubleSpinBox_hcat->setMinimum(-9999);
        doubleSpinBox_hcat->setMaximum(9999.99);
        doubleSpinBox_hcat->setValue(0.497247);
        doubleSpinBox_mcat = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mcat->setObjectName(QStringLiteral("doubleSpinBox_mcat"));
        doubleSpinBox_mcat->setGeometry(QRect(885, 152, 101, 24));
        doubleSpinBox_mcat->setDecimals(6);
        doubleSpinBox_mcat->setMinimum(-9999);
        doubleSpinBox_mcat->setMaximum(9999.99);
        doubleSpinBox_mcat->setValue(0.000299);
        doubleSpinBox_mkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mkca->setObjectName(QStringLiteral("doubleSpinBox_mkca"));
        doubleSpinBox_mkca->setGeometry(QRect(884, 244, 101, 24));
        doubleSpinBox_mkca->setDecimals(6);
        doubleSpinBox_mkca->setMinimum(-9999);
        doubleSpinBox_mkca->setMaximum(9999.99);
        doubleSpinBox_mcas = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mcas->setObjectName(QStringLiteral("doubleSpinBox_mcas"));
        doubleSpinBox_mcas->setGeometry(QRect(884, 213, 101, 24));
        doubleSpinBox_mcas->setDecimals(6);
        doubleSpinBox_mcas->setMinimum(-9999);
        doubleSpinBox_mcas->setMaximum(9999.99);
        label_90 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(838, 248, 61, 15));
        label_91 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(841, 156, 61, 15));
        label_92 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(843, 187, 61, 15));
        label_93 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(839, 217, 61, 15));
        doubleSpinBox_mkd = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mkd->setObjectName(QStringLiteral("doubleSpinBox_mkd"));
        doubleSpinBox_mkd->setGeometry(QRect(883, 303, 101, 24));
        doubleSpinBox_mkd->setDecimals(6);
        doubleSpinBox_mkd->setMinimum(-9999);
        doubleSpinBox_mkd->setMaximum(9999.99);
        doubleSpinBox_mkd->setValue(0.014577);
        doubleSpinBox_hkca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_hkca->setObjectName(QStringLiteral("doubleSpinBox_hkca"));
        doubleSpinBox_hkca->setGeometry(QRect(883, 272, 101, 24));
        doubleSpinBox_hkca->setDecimals(6);
        doubleSpinBox_hkca->setMinimum(-9999);
        doubleSpinBox_hkca->setMaximum(9999.99);
        doubleSpinBox_hkca->setValue(0.891752);
        doubleSpinBox_Ca = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_Ca->setObjectName(QStringLiteral("doubleSpinBox_Ca"));
        doubleSpinBox_Ca->setGeometry(QRect(881, 454, 101, 24));
        doubleSpinBox_Ca->setDecimals(6);
        doubleSpinBox_Ca->setMinimum(-9999);
        doubleSpinBox_Ca->setMaximum(9999.99);
        doubleSpinBox_Ca->setValue(0.04);
        doubleSpinBox_ha1 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_ha1->setObjectName(QStringLiteral("doubleSpinBox_ha1"));
        doubleSpinBox_ha1->setGeometry(QRect(882, 364, 101, 24));
        doubleSpinBox_ha1->setDecimals(6);
        doubleSpinBox_ha1->setMinimum(-9999);
        doubleSpinBox_ha1->setMaximum(9999.99);
        doubleSpinBox_ha1->setValue(0.614612);
        doubleSpinBox_mm = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mm->setObjectName(QStringLiteral("doubleSpinBox_mm"));
        doubleSpinBox_mm->setGeometry(QRect(881, 485, 101, 24));
        doubleSpinBox_mm->setDecimals(6);
        doubleSpinBox_mm->setMinimum(-9999);
        doubleSpinBox_mm->setMaximum(9999.99);
        doubleSpinBox_mm->setValue(0.017216);
        label_94 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(841, 489, 61, 15));
        doubleSpinBox_ma = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_ma->setObjectName(QStringLiteral("doubleSpinBox_ma"));
        doubleSpinBox_ma->setGeometry(QRect(882, 333, 101, 24));
        doubleSpinBox_ma->setDecimals(6);
        doubleSpinBox_ma->setMinimum(-9999);
        doubleSpinBox_ma->setMaximum(9999.99);
        doubleSpinBox_ma->setValue(0.113476);
        doubleSpinBox_ha2 = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_ha2->setObjectName(QStringLiteral("doubleSpinBox_ha2"));
        doubleSpinBox_ha2->setGeometry(QRect(882, 393, 101, 24));
        doubleSpinBox_ha2->setDecimals(6);
        doubleSpinBox_ha2->setMinimum(-9999);
        doubleSpinBox_ha2->setMaximum(9999.99);
        doubleSpinBox_ha2->setValue(0.133255);
        label_95 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(843, 368, 61, 15));
        label_96 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_96->setObjectName(QStringLiteral("label_96"));
        label_96->setGeometry(QRect(843, 397, 61, 15));
        label_97 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_97->setObjectName(QStringLiteral("label_97"));
        label_97->setGeometry(QRect(840, 276, 61, 15));
        label_98 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_98->setObjectName(QStringLiteral("label_98"));
        label_98->setGeometry(QRect(840, 307, 61, 15));
        label_99 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_99->setObjectName(QStringLiteral("label_99"));
        label_99->setGeometry(QRect(846, 458, 61, 15));
        label_100 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_100->setObjectName(QStringLiteral("label_100"));
        label_100->setGeometry(QRect(845, 428, 61, 15));
        label_101 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_101->setObjectName(QStringLiteral("label_101"));
        label_101->setGeometry(QRect(844, 337, 61, 15));
        doubleSpinBox_mh = new QDoubleSpinBox(NM_GUI_Nowotny_et_al_2008);
        doubleSpinBox_mh->setObjectName(QStringLiteral("doubleSpinBox_mh"));
        doubleSpinBox_mh->setGeometry(QRect(882, 424, 101, 24));
        doubleSpinBox_mh->setDecimals(6);
        doubleSpinBox_mh->setMinimum(-9999);
        doubleSpinBox_mh->setMaximum(9999.99);
        doubleSpinBox_mh->setValue(0.156078);
        label_102 = new QLabel(NM_GUI_Nowotny_et_al_2008);
        label_102->setObjectName(QStringLiteral("label_102"));
        label_102->setGeometry(QRect(830, 12, 141, 16));
        label_102->setFont(font);
        groupBox_IntegrationMethod = new QGroupBox(NM_GUI_Nowotny_et_al_2008);
        groupBox_IntegrationMethod->setObjectName(QStringLiteral("groupBox_IntegrationMethod"));
        groupBox_IntegrationMethod->setGeometry(QRect(810, 538, 181, 61));
        comboBoxIntegrationMethod = new QComboBox(groupBox_IntegrationMethod);
        comboBoxIntegrationMethod->setObjectName(QStringLiteral("comboBoxIntegrationMethod"));
        comboBoxIntegrationMethod->setEnabled(true);
        comboBoxIntegrationMethod->setGeometry(QRect(10, 30, 161, 23));
        pushButton_accept = new QPushButton(NM_GUI_Nowotny_et_al_2008);
        pushButton_accept->setObjectName(QStringLiteral("pushButton_accept"));
        pushButton_accept->setGeometry(QRect(860, 618, 82, 23));

        retranslateUi(NM_GUI_Nowotny_et_al_2008);

        comboBoxIntegrationMethod->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(NM_GUI_Nowotny_et_al_2008);
    } // setupUi

    void retranslateUi(QWidget *NM_GUI_Nowotny_et_al_2008)
    {
        NM_GUI_Nowotny_et_al_2008->setWindowTitle(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Nowotny et al (2008) neuron model", Q_NULLPTR));
        label->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I", Q_NULLPTR));
        label_2->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "IOffset", Q_NULLPTR));
        label_3->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "IScale", Q_NULLPTR));
        label_4->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Cm Soma", Q_NULLPTR));
        label_5->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Cm Axon", Q_NULLPTR));
        label_6->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Area Soma", Q_NULLPTR));
        label_7->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gvv", Q_NULLPTR));
        label_8->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Area Axon", Q_NULLPTR));
        label_9->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gna", Q_NULLPTR));
        label_10->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vna", Q_NULLPTR));
        label_11->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vkd", Q_NULLPTR));
        label_12->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gkd", Q_NULLPTR));
        label_13->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Pca", Q_NULLPTR));
        label_14->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Caout", Q_NULLPTR));
        label_15->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "RTF", Q_NULLPTR));
        label_16->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Ca0", Q_NULLPTR));
        label_17->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "cica", Q_NULLPTR));
        label_18->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "khcat", Q_NULLPTR));
        label_19->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vmcat", Q_NULLPTR));
        label_20->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kmcat", Q_NULLPTR));
        label_21->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vhcat", Q_NULLPTR));
        label_22->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gcat", Q_NULLPTR));
        label_23->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Skhcat", Q_NULLPTR));
        label_24->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Shcat", Q_NULLPTR));
        label_25->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Smcat", Q_NULLPTR));
        label_26->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vkhcat", Q_NULLPTR));
        label_27->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kmcas", Q_NULLPTR));
        label_28->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vmcas", Q_NULLPTR));
        label_29->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gcas", Q_NULLPTR));
        label_30->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Smcas", Q_NULLPTR));
        label_31->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "DC current", Q_NULLPTR));
        label_32->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Membrane potential", Q_NULLPTR));
        label_33->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_Na", Q_NULLPTR));
        label_34->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_Kd", Q_NULLPTR));
        label_35->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_Ca", Q_NULLPTR));
        label_36->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_CaT", Q_NULLPTR));
        label_37->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_CaS", Q_NULLPTR));
        label_38->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Smkca1", Q_NULLPTR));
        label_39->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vmkca1", Q_NULLPTR));
        label_40->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kmkca", Q_NULLPTR));
        label_41->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gkca", Q_NULLPTR));
        label_42->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vkca", Q_NULLPTR));
        label_43->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "f", Q_NULLPTR));
        label_44->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "khkca", Q_NULLPTR));
        label_45->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Smkca2", Q_NULLPTR));
        label_46->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vmkca2", Q_NULLPTR));
        label_47->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_KCa", Q_NULLPTR));
        label_48->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kca", Q_NULLPTR));
        label_49->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "cmkca", Q_NULLPTR));
        label_50->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "chkca2", Q_NULLPTR));
        label_51->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "chkca1", Q_NULLPTR));
        label_52->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vma", Q_NULLPTR));
        label_53->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "ga", Q_NULLPTR));
        label_54->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kha2", Q_NULLPTR));
        label_55->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Va", Q_NULLPTR));
        label_56->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vha", Q_NULLPTR));
        label_57->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vkha2", Q_NULLPTR));
        label_58->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kma", Q_NULLPTR));
        label_59->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kha1", Q_NULLPTR));
        label_60->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vaa", Q_NULLPTR));
        label_61->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Sha", Q_NULLPTR));
        label_62->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Skha2", Q_NULLPTR));
        label_63->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_A", Q_NULLPTR));
        label_64->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Sma", Q_NULLPTR));
        label_65->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Saa", Q_NULLPTR));
        label_66->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vl", Q_NULLPTR));
        label_67->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gl Soma", Q_NULLPTR));
        label_68->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gl Axon", Q_NULLPTR));
        label_69->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_Leak", Q_NULLPTR));
        label_70->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gh", Q_NULLPTR));
        label_71->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kmh", Q_NULLPTR));
        label_72->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vkmh", Q_NULLPTR));
        label_73->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vh", Q_NULLPTR));
        label_74->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_h", Q_NULLPTR));
        label_75->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Smh", Q_NULLPTR));
        label_76->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Skmh", Q_NULLPTR));
        label_77->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vmh", Q_NULLPTR));
        label_78->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "gm", Q_NULLPTR));
        label_79->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "kmm", Q_NULLPTR));
        label_80->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Smm", Q_NULLPTR));
        label_81->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vm", Q_NULLPTR));
        label_82->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "I_M", Q_NULLPTR));
        label_83->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vkmm", Q_NULLPTR));
        label_84->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Skmm", Q_NULLPTR));
        label_85->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vmm", Q_NULLPTR));
        label_86->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "V", Q_NULLPTR));
        label_87->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Vaxon", Q_NULLPTR));
        label_88->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mna", Q_NULLPTR));
        label_89->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "hna", Q_NULLPTR));
        label_90->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mkca", Q_NULLPTR));
        label_91->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mcat", Q_NULLPTR));
        label_92->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "hcat", Q_NULLPTR));
        label_93->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mcas", Q_NULLPTR));
        label_94->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mm", Q_NULLPTR));
        label_95->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "ha1", Q_NULLPTR));
        label_96->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "ha2", Q_NULLPTR));
        label_97->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "hkca", Q_NULLPTR));
        label_98->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mkd", Q_NULLPTR));
        label_99->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Ca", Q_NULLPTR));
        label_100->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "mh", Q_NULLPTR));
        label_101->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "ma", Q_NULLPTR));
        label_102->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Initial variables", Q_NULLPTR));
        groupBox_IntegrationMethod->setTitle(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Integration method", Q_NULLPTR));
        comboBoxIntegrationMethod->clear();
        comboBoxIntegrationMethod->insertItems(0, QStringList()
         << QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Euler", Q_NULLPTR)
         << QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Heun", Q_NULLPTR)
         << QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Runge-Kutta 4", Q_NULLPTR)
         << QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Runge-Kutta (6)5", Q_NULLPTR)
        );
        pushButton_accept->setText(QApplication::translate("NM_GUI_Nowotny_et_al_2008", "Accept", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class NM_GUI_Nowotny_et_al_2008: public Ui_NM_GUI_Nowotny_et_al_2008 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NM_GUI_NOWOTNY_ET_AL_2008_H
